/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS 8.1
 */
public class ArrayForm extends javax.swing.JFrame {

    /**
     * Creates new form ArrayForm
     */
    public ArrayForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTNama = new javax.swing.JTextField();
        jTAlamat = new javax.swing.JTextField();
        jTUsia = new javax.swing.JTextField();
        jTGender = new javax.swing.JTextField();
        jTGoldar = new javax.swing.JTextField();
        jTStatus = new javax.swing.JTextField();
        jTKewarganegaraan = new javax.swing.JTextField();
        jTPraktek = new javax.swing.JTextField();
        jTSpesialis = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Pemilihan Dokter");

        jLabel3.setText("Pilih Dokter : ");

        jLabel4.setText("Identitas");

        jLabel5.setText("Nama :");

        jLabel6.setText("Alamat : ");

        jLabel7.setText("Usia : ");

        jLabel8.setText("Gender :");

        jLabel9.setText("Golongan darah :");

        jLabel10.setText("Status :");

        jLabel11.setText("Kewarganegaraan :");

        jLabel12.setText("Waktu Praktek : ");

        jLabel13.setText("Dokter Spesialis : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras", "DR. Anisa", "DR. Harun" }));
        jComboBox1.setName("combo1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTNama.setName("tNama"); // NOI18N
        jTNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNamaActionPerformed(evt);
            }
        });

        jTAlamat.setName("tAlamat"); // NOI18N
        jTAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAlamatActionPerformed(evt);
            }
        });

        jTUsia.setName("tUsia"); // NOI18N
        jTUsia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsiaActionPerformed(evt);
            }
        });

        jTGender.setName("tGender"); // NOI18N
        jTGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGenderActionPerformed(evt);
            }
        });

        jTGoldar.setName("tGoldar"); // NOI18N
        jTGoldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGoldarActionPerformed(evt);
            }
        });

        jTStatus.setName("tStatus"); // NOI18N
        jTStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTStatusActionPerformed(evt);
            }
        });

        jTKewarganegaraan.setName("tKewarganegaraan"); // NOI18N
        jTKewarganegaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTKewarganegaraanActionPerformed(evt);
            }
        });

        jTPraktek.setName("tWaktu"); // NOI18N
        jTPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPraktekActionPerformed(evt);
            }
        });

        jTSpesialis.setName("tSpesialis"); // NOI18N
        jTSpesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSpesialisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNama)
                                    .addComponent(jTAlamat)
                                    .addComponent(jTUsia)
                                    .addComponent(jTGender)
                                    .addComponent(jTGoldar)
                                    .addComponent(jTStatus)
                                    .addComponent(jTKewarganegaraan)
                                    .addComponent(jTPraktek)
                                    .addComponent(jTSpesialis)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTUsia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTKewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTPraktek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTSpesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNamaActionPerformed

    private void jTAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAlamatActionPerformed

    private void jTUsiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsiaActionPerformed

    private void jTGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGenderActionPerformed

    private void jTGoldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGoldarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGoldarActionPerformed

    private void jTStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTStatusActionPerformed

    private void jTKewarganegaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTKewarganegaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTKewarganegaraanActionPerformed

    private void jTPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPraktekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPraktekActionPerformed

    private void jTSpesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSpesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSpesialisActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("DR. Farras")){ 
            jTNama.setText("DR. Farras Yassar "); 
            jTAlamat.setText("Jl. Surabaya 16, Malang"); 
            jTUsia.setText("20 Tahun"); 
            jTGender.setText("Laki-Laki"); 
            jTGoldar.setText("A"); 
            jTStatus.setText("Belum Menikah "); 
            jTKewarganegaraan.setText("Indonesia"); 
            jTSpesialis.setText("Dokter Umum"); 
            jTPraktek.setText(" Pagi (07.00-15.00)"); 
        } 
        else 
            if(jComboBox1.getSelectedItem().equals("DR. Anisa")){ 
            jTNama.setText("DR. Anisa Putri"); 
            jTAlamat.setText("Jl. Veteran 3, Malang"); 
            jTUsia.setText("20 Tahun"); 
            jTGender.setText("Perempuan"); 
            jTGoldar.setText("O"); 
            jTStatus.setText("Belum Menikah"); 
            jTKewarganegaraan.setText("Indonesia"); 
            jTSpesialis.setText("Dokter Gigi"); 
            jTPraktek.setText(" Sore (16.00-22.00)"); 
        } 
        else
                 if(jComboBox1.getSelectedItem().equals("DR. Harun")){ 
            jTNama.setText("DR. Harun Fajar "); 
            jTAlamat.setText("Jl. Bandung 9, Malang"); 
            jTUsia.setText("20 Tahun"); 
            jTGender.setText("Laki-Laki"); 
            jTGoldar.setText("B"); 
            jTStatus.setText("Belum Menikah"); 
            jTKewarganegaraan.setText("Indonesia"); 
            jTSpesialis.setText("Dokter Gizi"); 
            jTPraktek.setText(" Malam (22.00-06.00)"); 
        } 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTAlamat;
    private javax.swing.JTextField jTGender;
    private javax.swing.JTextField jTGoldar;
    private javax.swing.JTextField jTKewarganegaraan;
    private javax.swing.JTextField jTNama;
    private javax.swing.JTextField jTPraktek;
    private javax.swing.JTextField jTSpesialis;
    private javax.swing.JTextField jTStatus;
    private javax.swing.JTextField jTUsia;
    // End of variables declaration//GEN-END:variables
}
